version: "3.9"

services:
  backend:
    build: .
    container_name: petroplay_auto
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    mem_limit: 6g
    cpus: 4

