version: "3.9"

services:
  backend:
    build: .
    container_name: petroplus_api_python_container
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
